### ISSUE TITLE
Myprofile

### ISSUE THREAD

**Issue by eerison** [carlosjorger/cuvimaker#2]
Hello @carlosjorger   :) , in case you have sometime.

give a try in [myprofile project](https://github.com/shield-wall/myprofile), you can generate your resume just using yaml syntax in discussion section in github.

in the end, you will generate something like this: https://github.com/shield-wall/myprofile/discussions/723

**Comment by carlosjorger** [comment]
Cool. Your proyect sounds very interesting.I will check it. Thanks for comment👍
